sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
env:
  - BOTO_CONFIG=/tmp/nowhere
addons:
  apt:
    packages:
      - swig
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install -r requirements-py26.txt; fi
  - travis_retry pip install -r requirements.txt

script: python tests/test.py default

jobs:
  include:
    - stage: rpmlint
      before_install: skip
      install: skip
      script: make spec && docker run -v "$PWD"/python-boto.spec:/specs/python-boto.spec ubun/rpmlinter
